name: Build EXE com Nuitka

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install PySide6 nuitka zstandard

      - name: Compilar com Nuitka
        run: |
          python -m nuitka `
            --standalone `
            --onefile `
            --enable-plugin=pyside6 `
            --windows-console-mode=disable `
            --output-filename=TesteTarefas.exe `
            --output-dir=dist `
            --assume-yes-for-downloads `
            app.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: TesteTarefas
          path: dist/TesteTarefas.exe
